"""Create users and issues tables

Revision ID: 09cbc9be3975
Revises: 3f2d80960de8
Create Date: 2026-07-23 12:00:37.354644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09cbc9be3975'
down_revision = '3f2d80960de8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
