"""add comments and activity tables

Revision ID: a5dfac406bc3
Revises: 678b02fdd46b
Create Date: 2026-07-23 17:43:53.980990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5dfac406bc3'
down_revision = '678b02fdd46b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_id'), 'comments', ['id'], unique=False)
    op.create_table('issue_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('field_name', sa.String(length=50), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_issue_activities_id'), 'issue_activities', ['id'], unique=False)
    # Skip FK modification for SQLite - constraint already exists correctly
    # op.drop_constraint(None, 'issue_photos', type_='foreignkey')
    # op.create_foreign_key(None, 'issue_photos', 'issues', ['issue_id'], ['id'])
    op.alter_column('issues', 'issue_number',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.create_unique_constraint(None, 'issues', ['issue_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'issues', type_='unique')
    op.alter_column('issues', 'issue_number',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    # Skip FK modification for SQLite
    # op.drop_constraint(None, 'issue_photos', type_='foreignkey')
    # op.create_foreign_key(None, 'issue_photos', 'issues', ['issue_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_issue_activities_id'), table_name='issue_activities')
    op.drop_table('issue_activities')
    op.drop_index(op.f('ix_comments_id'), table_name='comments')
    op.drop_table('comments')
    # ### end Alembic commands ###
