"""add_visitor_logs_table

Revision ID: b5b1dc085bd0
Revises: f3g4h5i6j7k8
Create Date: 2026-08-05 10:34:45.230520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5b1dc085bd0'
down_revision = 'f3g4h5i6j7k8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        'visitor_logs',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('visitor_name', sa.String(), nullable=False),
        sa.Column('visitor_phone', sa.String(), nullable=True),
        sa.Column('vehicle_number', sa.String(), nullable=True),
        sa.Column('purpose', sa.String(), nullable=True),
        sa.Column('host_unit', sa.String(), nullable=False),
        sa.Column('host_user_id', sa.String(), nullable=True),
        sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'DENIED', 'CHECKED_OUT', name='visitorstatus'), nullable=False),
        sa.Column('check_in_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
        sa.Column('check_out_time', sa.DateTime(), nullable=True),
        sa.Column('logged_by', sa.String(), nullable=False),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['host_user_id'], ['users.id']),
        sa.ForeignKeyConstraint(['logged_by'], ['users.id']),
        sa.PrimaryKeyConstraint('id'),
    )


def downgrade() -> None:
    op.drop_table('visitor_logs')


def _dead_code_do_not_call() -> None:
    op.alter_column('comments', 'issue_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('comments', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_index('ix_contractor_profiles_user_id', table_name='contractor_profiles')
    op.create_index(op.f('ix_contractor_profiles_user_id'), 'contractor_profiles', ['user_id'], unique=True)
    op.alter_column('events', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('events', 'event_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('MEETING', 'FESTIVAL', 'MAINTENANCE', 'SOCIAL', 'SPORTS', 'OTHER', name='eventtype'),
               existing_nullable=False)
    op.alter_column('events', 'created_by',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('feedback', 'category',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.Enum('PROCESS', 'FACILITY', 'COMMUNICATION', 'SAFETY', 'GENERAL', name='feedbackcategory'),
               existing_nullable=False,
               existing_server_default=sa.text("'general'"))
    op.alter_column('feedback', 'status',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.Enum('PENDING', 'ACKNOWLEDGED', 'IN_REVIEW', 'IMPLEMENTED', 'REJECTED', name='feedbackstatus'),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'"))
    op.alter_column('issue_activities', 'issue_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('issue_activities', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_constraint(None, 'issue_photos', type_='foreignkey')
    op.create_foreign_key(None, 'issue_photos', 'issues', ['issue_id'], ['id'])
    op.alter_column('issues', 'issue_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('ix_work_completions_issue_id', table_name='work_completions')
    op.create_index(op.f('ix_work_completions_issue_id'), 'work_completions', ['issue_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_work_completions_issue_id'), table_name='work_completions')
    op.create_index('ix_work_completions_issue_id', 'work_completions', ['issue_id'], unique=False)
    op.alter_column('issues', 'issue_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'issue_photos', type_='foreignkey')
    op.create_foreign_key(None, 'issue_photos', 'issues', ['issue_id'], ['id'], ondelete='CASCADE')
    op.alter_column('issue_activities', 'user_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('issue_activities', 'issue_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('feedback', 'status',
               existing_type=sa.Enum('PENDING', 'ACKNOWLEDGED', 'IN_REVIEW', 'IMPLEMENTED', 'REJECTED', name='feedbackstatus'),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'"))
    op.alter_column('feedback', 'category',
               existing_type=sa.Enum('PROCESS', 'FACILITY', 'COMMUNICATION', 'SAFETY', 'GENERAL', name='feedbackcategory'),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False,
               existing_server_default=sa.text("'general'"))
    op.alter_column('events', 'created_by',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('events', 'event_type',
               existing_type=sa.Enum('MEETING', 'FESTIVAL', 'MAINTENANCE', 'SOCIAL', 'SPORTS', 'OTHER', name='eventtype'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('events', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_index(op.f('ix_contractor_profiles_user_id'), table_name='contractor_profiles')
    op.create_index('ix_contractor_profiles_user_id', 'contractor_profiles', ['user_id'], unique=False)
    op.alter_column('comments', 'user_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('comments', 'issue_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_table('visitor_logs')
    # ### end Alembic commands ###
