"""fix issue_id and user_id types to string

Revision ID: bcc753702a4e
Revises: a5dfac406bc3
Create Date: 2026-07-23 18:08:16.934263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcc753702a4e'
down_revision = 'a5dfac406bc3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite doesn't support ALTER COLUMN, so we need to recreate tables
    # Drop and recreate comments table with correct types
    op.drop_index('ix_comments_id', table_name='comments')
    op.drop_table('comments')
    op.create_table('comments',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('issue_id', sa.String(), nullable=False),
        sa.Column('user_id', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('is_deleted', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_comments_id', 'comments', ['id'], unique=False)
    
    # Drop and recreate issue_activities table with correct types
    op.drop_index('ix_issue_activities_id', table_name='issue_activities')
    op.drop_table('issue_activities')
    op.create_table('issue_activities',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('issue_id', sa.String(), nullable=False),
        sa.Column('user_id', sa.String(), nullable=True),
        sa.Column('action', sa.String(length=50), nullable=False),
        sa.Column('field_name', sa.String(length=50), nullable=True),
        sa.Column('old_value', sa.Text(), nullable=True),
        sa.Column('new_value', sa.Text(), nullable=True),
        sa.Column('description', sa.Text(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_issue_activities_id', 'issue_activities', ['id'], unique=False)
    
    # Skip FK modifications for SQLite compatibility
    # op.drop_constraint(None, 'issue_photos', type_='foreignkey')
    # op.create_foreign_key(None, 'issue_photos', 'issues', ['issue_id'], ['id'])
    
    # Fix issues table
    with op.batch_alter_table('issues') as batch_op:
        batch_op.alter_column('issue_number',
                   existing_type=sa.TEXT(),
                   type_=sa.String(),
                   nullable=False)
        batch_op.create_unique_constraint('uq_issues_issue_number', ['issue_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issues') as batch_op:
        batch_op.drop_constraint('uq_issues_issue_number', type_='unique')
        batch_op.alter_column('issue_number',
                   existing_type=sa.String(),
                   type_=sa.TEXT(),
                   nullable=True)
    
    # Drop and recreate tables with old INTEGER types
    op.drop_index('ix_issue_activities_id', table_name='issue_activities')
    op.drop_table('issue_activities')
    op.create_table('issue_activities',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('issue_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('action', sa.String(length=50), nullable=False),
        sa.Column('field_name', sa.String(length=50), nullable=True),
        sa.Column('old_value', sa.Text(), nullable=True),
        sa.Column('new_value', sa.Text(), nullable=True),
        sa.Column('description', sa.Text(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_issue_activities_id', 'issue_activities', ['id'], unique=False)
    
    op.drop_index('ix_comments_id', table_name='comments')
    op.drop_table('comments')
    op.create_table('comments',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('issue_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('is_deleted', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_comments_id', 'comments', ['id'], unique=False)
    # ### end Alembic commands ###
